### ISSUE TITLE
AttributeError: module 'ctypes' has no attribute 'windll'

### ISSUE THREAD

**Issue by adminradio** [blenderskool/kaleidoscope#21]
### Blender throws the following exception in varius situations using Kaleidoskop

```
Traceback (most recent call last):
File "[...snip...]/2.78/scripts/addons/kaleidoscope-master/client.py", line 300, \LF
in execute ctypes.windll.user32.keybd_event(VK_ESCAPE)
AttributeError: module 'ctypes' has no attribute 'windll'

location: <unknown location>:-1
```
### Running Blender 2.78c on MacOSX 10.12.4

In the following screenshot, clicking 'Yes' will throw the exception:
![screenshot-201704240413](https://cloud.githubusercontent.com/assets/2880143/25320118/7c84da28-28a4-11e7-8c5c-d05a63c7adc2.png)

If I search for `ctypes.windll.user32` in your code, there are other places you should have a look.

**Hint 1:** Blender is multi platform, so you should **not** use any windows specific dynamic libraries in addons for blender (or you should mention it in your plugin description that it will only run under windows).

**Hint 2:** This is only cosmetic, but you should also be aware of, that red button represents in most use cases an action which will be cancelled. Committing a change are usually associated with green buttons.

But never mind, I like the idea of your addon. ;)

**Comment by blenderskool** [comment]
Yes, that only works on Windows machine, I will fix that in the next version so that it works with all machines.

Since Blender's API does not allow colored buttons, it would not be possible to do that. Hence, I had to make it red so it stands out. I might change it to some icons that would be more understandable.
