### ISSUE TITLE
dont work with blender-2.79

### ISSUE THREAD

**Issue by brothermechanic** [blenderskool/kaleidoscope#23]
Traceback (most recent call last):
  File "/usr/share/blender/2.79/scripts/modules/addon_utils.py", line 331, in enable
    mod = __import__(module_name)
  File "/usr/share/blender/2.79/scripts/addons/blender-kaleidoscope-9999/__init__.py", line 21, in <module>
    from . import spectrum, intensity, addon_updater_ops, color_picker
  File "/usr/share/blender/2.79/scripts/addons/blender-kaleidoscope-9999/spectrum.py", line 1270
    global online_check
    ^
SyntaxError: name 'online_check' is assigned to before global declaration

**Comment by blenderskool** [comment]
Please check if the add-on is not modified. The line which shows error does not correspond to the error mentioned. You can download the latest release and check if it works.

**Comment by brothermechanic** [comment]
Ok, i found a problem
Your addon is for python-3.5
My blender is on python-3.6
Please try to run kaleidoscope on python-3.6 (blender-2.79.1 support only python-3.6)
I hope you fix this bug.

**Comment by blenderskool** [comment]
Thanks for pointing out, will work on it :+1:

**Comment by blenderskool** [comment]
Fixed it :smiley:

**Comment by brothermechanic** [comment]
Wow!
Cool! Thank you!
