### ISSUE TITLE
create INTENSITY NODE make live render viewport keep refreshing[blender2.79b]

### ISSUE THREAD

**Issue by mido6482** [blenderskool/kaleidoscope#30]
create INTENSITY NODE make live render viewport keep refreshing _flickering_ [try it in blender2.79b and blender2.79-b618c185cb7]
viewport will back to normal again if i only delete the node
any solution please ?
[space_02.zip](https://github.com/blenderskool/kaleidoscope/files/2476675/space_02.zip)

**Comment by blenderskool** [comment]
Which operating system are you using? Also, can you share a gif/video of the viewport flickering?

**Comment by mido6482** [comment]
win 10 1809 x64 
ram 16 GB 
cpu FX8350
gpu 1050TI
https://youtu.be/AZnhx4bivtg

**Comment by blenderskool** [comment]
Thanks for the additional info, looks like a bug to me
