### ISSUE TITLE
Blender 2.8 compatibility

### ISSUE THREAD

**Issue by blenderskool** [blenderskool/kaleidoscope#33]
Make add-on compatible with Blender 2.8

**Comment by kenwud** [comment]
i would love to see this addon updated for 2.8

**Comment by schroef** [comment]
Im almost done with it, i need to clean it and get the last errors out.

PS why is cgcookie updater in here while its not doing anything?

**Comment by schroef** [comment]
I got the updater to work now, updated it to the newer version. I do see one issue. The addone in blender is 1.0.5 but on on gitHub you tagged it as 1.05 so it thinks its a newer version

<img width="362" alt="Screen Shot 2020-01-29 at 20 15 39" src="https://user-images.githubusercontent.com/6923008/73408947-2507f580-42d4-11ea-8d34-a1d6adf704f7.png">

**Comment by schroef** [comment]
Changing the addon to 1.5.0 fixes this. But then its not consistent with your dev branch

<img width="437" alt="Screen Shot 2020-01-29 at 20 41 58" src="https://user-images.githubusercontent.com/6923008/73410219-f9870a00-42d7-11ea-80e8-01526b62e081.png">

**Comment by blenderskool** [comment]
@schroef Thanks for taking the initiative. I am busy with other projects right now, hence it's still not updated to Blender 2.8x

**Comment by blenderskool** [comment]
@schroef @kenwud Addon has been updated to work with Blender 2.81 and above. Check this for the update https://github.com/blenderskool/kaleidoscope/releases/tag/v1.1.0
