### ISSUE TITLE
From blank install save palette has issue

### ISSUE THREAD

**Issue by schroef** [blenderskool/kaleidoscope#34]
Im trying to update the addon to 2.80 and i had big issues getting it to run. Now i think i got but it seems the save palette part is having an issue. If no files are there nothing is there to show in the enum menu. Is that correct, because i do see the button show for add and save.

I tried adding a blanc one to the list, but that gave another issue with loading correct order and naming issues aswell as no colors available.
<img width="262" alt="Screen Shot 2020-01-30 at 00 30 55" src="https://user-images.githubusercontent.com/6923008/73420133-dff5ba80-42f7-11ea-9e9f-b76ad8d98771.png">
But on saving still no menu

I also get this error, which i can not get away. I cant remember what the srna issue
```
WARN (bpy.rna): /Users/gast/blender-buildbot/mac_x86_64_10_9_cmake/blender.git/source/blender/python/intern/bpy_rna.c:1476 pyrna_enum_to_py: current value '0' matches no enum in 'SpectrumProperties', '', 'saved_palettes'
```

**Comment by blenderskool** [comment]
@schroef Thanks for letting me know. I was planning on rethinking some parts of the add-on(especially saving and managing palettes). It's been a long time since I first developed this add-on and I have since learned more advanced and better ways to handle this.

**Comment by blenderskool** [comment]
@schroef While this issue is still present, the srna issue is mostly a warning and not something that causes errors. Let me know if there is any solution for this, we can work on this issue then.
